# Generated by Django 5.2 on 2025-04-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.IntegerField(null=True),
        ),
    ]
