# Generated by Django 5.2 on 2025-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='president',
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('coordinator', 'Coordinator')], default='member', max_length=20),
        ),
    ]
