# Generated by Django 5.2 on 2025-04-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_club_president_alter_club_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TextField(),
        ),
    ]
